//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FootballLeagueEntities : DbContext, IDBContext
    {
        public FootballLeagueEntities()
            : base("name=FootballLeagueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    
        public virtual int RefreshResults()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RefreshResults");
        }
    }
}
