//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace DataBase
{
    public interface IFootballLeagueEntities
    {
        DbSet<Matches> Matches { get; set; }
        DbSet<Teams> Teams { get; set; }
    }
}